### ISSUE TITLE
Componentizar validação e estilo dos fields

### ISSUE THREAD

**Issue by felipealencar** [lead-ifal/pc2i-app#13]
Dá uma olhada no TextFormField e no Form, e como se faz validação com a chave que controla o estado do formulário. Desta forma você conseguira fazer validações bem mais elaboradas e com menos código. Isso vai ajudar muito na segurança dos dados passados nos inputs.

Independente de você optar pelo TextField ou o TextFormField é interessante que você componentize, deixando o widget com o modelo que desejas e com ele personalizado basta só passar os atributos necessários. Ex.: Em todos os TextField você está colocando um estilo de borda arredondada, se você componentizar não precisará adicionar isso todas as vezes que chamar o widget.

_Originally posted by @dhianaslv in https://github.com/lead-ifal/pc2i-app/pull/12#r707857655_

**Comment by felipealencar** [comment]
@filipealvess essa arquitetura foi seguida?

**Comment by filipealvess** [comment]
Foi sim, @felipealencar.

> Dá uma olhada no TextFormField e no Form, e como se faz validação com a chave que controla o estado do formulário.

- A utilização da chave do formulário foi feita no PR #22.

> Independente de você optar pelo TextField ou o TextFormField é interessante que você componentize

- Esse componente de *input* já existia, mas não foi utilizado na primeira implementação da tela. Para corrigir esse erro de implementação, foi criado o PR #19.
