### ISSUE TITLE
Error: No file or variants found for asset: .env

### ISSUE THREAD

**Issue by dhianaslv** [lead-ifal/pc2i-app#16]
https://github.com/lead-ifal/pc2i-app/blob/d5af48c74860b6c95fb44ee798f88708c364efe1/lib/main.dart#L6

Interessante esse flutter_dotenv, mas fui rodar o projeto e deu erro por não encontrar esse .env. Então, fui dar uma olhada no .gitignore, não sei se é por isso que ele não está encontrando o arquivo, mas talvez seja.

@filipealvess, eu vi que essa utilização do flutter_dotenv foi para cumprir o que foi pedido pelo Prof. @felipealencar (https://github.com/lead-ifal/pc2i-app/pull/6#discussion_r702172817), mas acho que uma forma legal de fazer isso, sem precisar usar esse pacote, é justamente usando essa classe Config onde você tem a base da url e puxar ela em outros arquivos por meio do get.

**Comment by felipealencar** [comment]
@dhianaslv @filipealvess a questão do .env é que irá permitir que a gente com mudanças simples possa configurar diferentes instâncias do App em cada cliente.

@filipealvess, quando possível, adiciona um .env_example (algo assim) para que sirva de modelo.
