### ISSUE TITLE
Criar arquivo .env de exemplo e commitar no repositório.

### ISSUE THREAD

**Issue by felipealencar** [lead-ifal/pc2i-app#17]
@dhianaslv @filipealvess a questão do .env é que irá permitir que a gente com mudanças simples possa configurar diferentes instâncias do App em cada cliente.

@filipealvess, quando possível, adiciona um .env_example (algo assim) para que sirva de modelo.

_Originally posted by @felipealencar in https://github.com/lead-ifal/pc2i-app/issues/16#issuecomment-938096386_

**Comment by filipealvess** [comment]
@dhianaslv, acabei de fazer um novo clone do projeto para ter um contexto mais próximo do seu.

Eu obtive apenas este erro: `Error: Instance of 'EmptyEnvFileError'`, que aconteceu porque o arquivo `.env` estava vazio. Logo em seguida, preenchi este arquivo com o conteúdo do arquivo `.env-example` e rodou normal.

É esse erro que está aparecendo na sua máquina?

**Comment by dhianaslv** [comment]
Não, não é. Segue o erro que está dando,
`
Error detected in pubspec.yaml:
No file or variants found for asset: .env.
`

Olhei aqui e realmente este `.env` não existe, pelo menos não quando eu clono o repositório (Já fiz isso duas vezes). A solução que achei foi parecida com a sua, mas em vez de preencher o `.env` com o conteúdo do `.env-example,` eu adicionei o `.env-example` no `pubspec.yaml` e na `main` também. Desse jeito:

`await dotenv.load(fileName: '.env-example');`

Dessa forma rodou sem problemas.

**Comment by felipealencar** [comment]
Fechando de acordo com informação que @filipealvess passou. O arquivo já se encontra no repositório.
