### ISSUE TITLE
Problema na comunicação entre App e API no Windows

### ISSUE THREAD

**Issue by filipealvess** [lead-ifal/pc2i-app#25]
O uso dos dados do arquivo `.env-example` funciona perfeitamente quando o app e a API são executados no Linux (imagino que o mesmo ocorre no macOS), mas no Windows pode acontecer o erro `SocketException: OS Error: Connection refused`.

De acordo com a solução apresentada [nessa questão do StackOverflow](https://stackoverflow.com/questions/55785581/socketexception-os-error-connection-refused-errno-111-in-flutter-using-djan), o problema está no formato da URL.

Atualmente a requisição realizada pelo app à API está sendo feita para a rota `http://127.0.0.1:5000/<...>`. Porém, no Windows ela deveria ser `http://10.0.2.2:5000/<...>`.

@felipealencar, é uma boa a gente atualizar o `.env-example` e o `README.md` com essas informações ;)

**Comment by felipealencar** [comment]
Legal, Filipe!
Vou adicionar.
